# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('cod_bebida', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_bebida', models.CharField(max_length=30)),
                ('precio_bebida', models.FloatField()),
                ('disponibilidad_bebida', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Capacidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_capacidad', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cod_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_categoria', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('cod_comida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comida', models.CharField(max_length=20)),
                ('descripcion_comida', models.TextField(max_length=150)),
                ('precio_comida', models.FloatField()),
                ('disponibilidad_comida', models.BooleanField()),
                ('categoria', models.ManyToManyField(to='producto.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen_Bebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_bebida', models.ImageField(upload_to='img_bebidas')),
                ('bebida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='producto.Bebida')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen_Comida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_comida', models.ImageField(upload_to='img_comidas')),
                ('comida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='producto.Comida')),
            ],
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_linea', models.TextField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='bebida',
            name='capacidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Capacidad'),
        ),
        migrations.AddField(
            model_name='bebida',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Linea'),
        ),
    ]
