# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('cod_bebida', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('nombre_bebida', models.CharField(max_length=30)),
                ('precio_bebida', models.FloatField()),
                ('disponibilidad_bebida', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Capacidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_capacidad', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cod_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('cod_comida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comida', models.CharField(max_length=20)),
                ('descripcion_comida', models.CharField(max_length=50)),
                ('precio_comida', models.FloatField()),
                ('disponibilidad_comida', models.BooleanField()),
                ('categoria', models.ManyToManyField(to='producto.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen_Bebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen_Comida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_linea', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='bebida',
            name='capacidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Capacidad'),
        ),
        migrations.AddField(
            model_name='bebida',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Linea'),
        ),
    ]
