# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='descripcion',
            new_name='descripcion_categoria',
        ),
    ]
