# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_comida_comercio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen_bebida',
            name='bebida',
        ),
        migrations.RemoveField(
            model_name='imagen_comida',
            name='comida',
        ),
        migrations.RemoveField(
            model_name='bebida',
            name='linea',
        ),
        migrations.AddField(
            model_name='bebida',
            name='categoria',
            field=models.ManyToManyField(to='producto.Categoria'),
        ),
        migrations.AddField(
            model_name='bebida',
            name='imagen',
            field=models.ImageField(null=True, upload_to='img_bebidas'),
        ),
        migrations.AddField(
            model_name='comida',
            name='imagen',
            field=models.ImageField(null=True, upload_to='img_comidas'),
        ),
        migrations.DeleteModel(
            name='Imagen_Bebida',
        ),
        migrations.DeleteModel(
            name='Imagen_Comida',
        ),
        migrations.DeleteModel(
            name='Linea',
        ),
    ]
