# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20161103_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comida',
            name='comercio',
        ),
    ]
