# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0007_auto_20161103_2148'),
        ('producto', '0004_remove_comida_comercio'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='comercio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comercio.Comercio'),
        ),
    ]
