# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_auto_20161103_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacidad',
            name='codigo',
            field=models.CharField(default='00000', max_length=5),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
