# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_auto_20161105_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacidad',
            name='codigo',
            field=models.CharField(max_length=30),
        ),
    ]
