# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_auto_20161105_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Bebida',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='bebida',
            name='categoria',
            field=models.ManyToManyField(to='producto.Categoria_Bebida'),
        ),
    ]
