# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0009_auto_20161105_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='descuento',
            field=models.FloatField(default=0.0),
        ),
    ]
