# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0012_auto_20161105_1959'),
        ('producto', '0010_comida_descuento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img_promociones')),
                ('descripcion', models.TextField(max_length=200)),
                ('precio', models.FloatField()),
                ('comercio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comercio.Comercio')),
            ],
        ),
    ]
