# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 20:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0011_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='fecha_caducidad',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
