# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('cod_comercio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cadena', models.CharField(max_length=40)),
                ('nombre_comercio', models.CharField(max_length=40)),
                ('rubro', models.CharField(max_length=20)),
                ('horarios', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('cod_domicilio', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=50)),
                ('nro_calle', models.IntegerField()),
                ('cod_localidad', models.IntegerField()),
                ('coordenadas', models.CharField(max_length=30)),
                ('comercio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comercio.Comercio')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('cod_pago', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.Comercio')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('nro_tel', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.Comercio')),
            ],
        ),
    ]
