# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('rubro', models.CharField(max_length=20)),
                ('horarios', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=150)),
                ('disponibilidad', models.BooleanField()),
                ('imagen', models.ImageField(upload_to='img_comercios')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('coordenadas', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=50)),
                ('disponibilidad', models.BooleanField()),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.Comercio')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('numero', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=30)),
                ('disponibilidad', models.BooleanField()),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.Comercio')),
            ],
        ),
        migrations.AddField(
            model_name='domicilio',
            name='localidad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comercio.Localidad'),
        ),
        migrations.AddField(
            model_name='comercio',
            name='domicilio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comercio.Domicilio'),
        ),
    ]
