# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='telefono',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='comercio.Telefono'),
        ),
    ]
