# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_remove_comida_comercio'),
        ('comercio', '0002_remove_pago_comercio'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='comida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.Comida'),
        ),
    ]
