# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0002_auto_20161014_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='telefono',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comercio.Telefono'),
        ),
    ]
