# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0004_auto_20161103_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domicilio',
            name='localidad',
        ),
        migrations.AddField(
            model_name='comercio',
            name='latitud',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='comercio',
            name='localidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comercio.Localidad'),
        ),
        migrations.AddField(
            model_name='comercio',
            name='longitud',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='domicilio',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Domicilio',
        ),
    ]
