# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0005_auto_20161103_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comercio',
            name='comida',
        ),
    ]
