# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0006_remove_comercio_comida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefono',
            name='comercio',
        ),
        migrations.RemoveField(
            model_name='telefono',
            name='disponibilidad',
        ),
        migrations.AddField(
            model_name='comercio',
            name='forma_pago',
            field=models.ManyToManyField(to='comercio.Pago'),
        ),
        migrations.AddField(
            model_name='comercio',
            name='telefonos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comercio.Telefono'),
        ),
    ]
