# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0007_auto_20161103_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='telefono',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='comercio',
            name='rubro',
        ),
        migrations.AddField(
            model_name='comercio',
            name='rubro',
            field=models.ManyToManyField(to='comercio.Rubro'),
        ),
    ]
