# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0008_auto_20161105_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comercio',
            name='telefonos',
        ),
        migrations.AddField(
            model_name='comercio',
            name='telefono',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Telefono',
        ),
    ]
