# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0009_auto_20161105_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rubro',
            old_name='descripcion',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='disponibilidad',
        ),
    ]
