# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0011_auto_20161105_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='delivery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='comercio.Delivery'),
        ),
    ]
