# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0012_auto_20161105_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='comercio',
            name='telefono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comercio.Telefono'),
        ),
    ]
