# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0014_auto_20161105_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='visitas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
