# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0015_comercio_visitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='delivery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comercio.Delivery'),
        ),
    ]
