# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0016_auto_20161106_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='latitud',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='comercio',
            name='localidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comercio.Localidad'),
        ),
        migrations.AddField(
            model_name='comercio',
            name='longitud',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
