# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 11:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0017_auto_20161108_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 9, 11, 49, 39, 634339)),
        ),
    ]
