# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0018_comercio_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='visitas',
            field=models.IntegerField(default=0),
        ),
    ]
