# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0019_auto_20161109_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='apertura',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
