# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0020_comercio_apertura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('apertura', models.TimeField()),
                ('cierre', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='comercio',
            name='apertura',
        ),
        migrations.AlterField(
            model_name='comercio',
            name='horarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.Horario'),
        ),
    ]
