# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0021_auto_20161109_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='horarios',
            field=models.CharField(max_length=30),
        ),
    ]
