# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0022_auto_20161109_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='horarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.Horario'),
        ),
    ]
